export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';


export const POST_JOB_REQUEST = 'POST_JOB_REQUEST';
export const POST_JOB_SUCCESS = 'POST_JOB_SUCCESS';
export const POST_JOB_FAIL = 'POST_JOB_FAIL';


export const FETCH_JOB_REQUEST = 'FETCH_JOB_REQUEST';
export const FETCH_JOB_SUCCESS = 'FETCH_JOB_SUCCESS';
export const FETCH_JOB_FAIL = 'FETCH_JOB_FAIL';

export const TOGGLE = 'TOGGLE';




export const JOB_APPLY_REQUEST = 'JOB_APPLY_REQUEST';
export const JOB_APPLY_SUCCESS = 'JOB_APPLY_SUCCESS';
export const JOB_APPLY_FAIL = 'JOB_APPLY_FAIL';




export const RECRUITER_FETCH_JOB_REQUEST = 'RECRUITER_FETCH_JOB_REQUEST';
export const RECRUITER_FETCH_JOB_SUCCESS = 'RECRUITER_FETCH_JOB_SUCCESS';
export const RECRUITER_FETCH_JOB_FAIL = 'RECRUITER_FETCH_JOB_FAIL';





export const RECRUITER_DELETE_JOB_SUCCESS = 'RECRUITER_DELETE_JOB_SUCCESS';
export const RECRUITER_DELETE_JOB_FAIL = 'RECRUITER_DELETE_JOB_FAIL';
export const RECRUITER_DELETE_JOB_REQUEST = 'RECRUITER_DELETE_JOB_REQUEST';






export const EDIT_JOB_REQUEST = 'EDIT_JOB_REQUEST';
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS';
export const EDIT_JOB_FAIL = 'EDIT_JOB_FAIL';




export const SEEKER_FETCH_JOB_FAIL = 'SEEKER_FETCH_JOB_FAIL';
export const SEEKER_FETCH_JOB_SUCCESS = 'SEEKER_FETCH_JOB_SUCCESS';
export const SEEKER_FETCH_JOB_REQUEST = 'SEEKER_FETCH_JOB_REQUEST';



export const RECRUITER_REGISTER_FAIL = 'RECRUITER_REGISTER_FAIL';
export const RECRUITER_REGISTER_SUCCESS = 'RECRUITER_REGISTER_SUCCESS';
export const RECRUITER_REGISTER_REQUEST = 'RECRUITER_REGISTER_REQUEST';





export const SEEKER_REGISTER_FAIL = 'SEEKER_REGISTER_FAIL';
export const SEEKER_REGISTER_SUCCESS = 'SEEKER_REGISTER_SUCCESS';
export const SEEKER_REGISTER_REQUEST = 'SEEKER_REGISTER_REQUEST';





export const RECRUITER_FETCH_LIST_SEEKER_FAIL = 'RECRUITER_FETCH_LIST_SEEKER_FAIL';
export const RECRUITER_FETCH_LIST_SEEKER_SUCCESS = 'RECRUITER_FETCH_LIST_SEEKER_SUCCESS';
export const RECRUITER_FETCH_LIST_SEEKER_REQUEST = 'RECRUITER_FETCH_LIST_SEEKER_REQUEST';




export const RECRUITER_DOWNLOAD_FILE_REQUEST = 'RECRUITER_DOWNLOAD_FILE_REQUEST';
export const RECRUITER_DOWNLOAD_FILE_SUCCESS = 'RECRUITER_DOWNLOAD_FILE_SUCCESS';
export const RECRUITER_DOWNLOAD_FILE_FAIL = 'RECRUITER_DOWNLOAD_FILE_FAIL';






export const FETCH_JOBINDEED_REQUEST = 'FETCH_JOBINDEED_REQUEST';
export const FETCH_JOBINDEED_SUCCESS = 'FETCH_JOBINDEED_SUCCESS';
export const FETCH_JOBINDEED_FAIL = 'FETCH_JOBINDEED_FAIL';

